services:
  unshortener:
    # Build the jar first: ./gradlew build
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: unshortener:latest
    restart: unless-stopped
    ports:
      - "9080:80"
#      - "9443:443"
    environment:
      QUARKUS_LOG_CATEGORY__COM_SNIGJI_UNSHORTENER__LEVEL: DEBUG
#      QUARKUS_HTTP_SSL_CERTIFICATE_FILES: /etc/unshortener/tls/tls.crt
#      QUARKUS_HTTP_SSL_CERTIFICATE_KEY_FILES: /etc/unshortener/tls/tls.key
#    volumes:
#      - ./certs:/etc/unshortener/tls:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/q/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
